server:
  port: 7000
spring:
  datasource:
    username: root
    password: mc666
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat  #开启监控过滤器
  redis:
    host: 192.168.18.201
    port: 6379
    password: 123456
application:
  name: SCW-USER
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mc/user/mapper/*.xml

logging:
    file:
      path: d:\log\scw-user
    level:
       mc: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
sms:
  host: http://dingxin.market.alicloudapi.com
  path: /dx/sendSms
  method: POST
  appcode: e36b5b26de9d49adade757f192f631d1

